use crate::{Attack, Family, Severity, Verdict};
use std::collections::BTreeMap;

#[derive(Debug, Clone, serde::Serialize)]
pub struct Finding {
    pub id: String,
    pub family: Family,
    pub technique: &'static str,
    pub severity: Severity,
    pub witnesses: Vec<String>,
    pub intent: &'static str,
    pub status: Status,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
pub enum Status {
    ClosedByHardening,
    Open,
}

impl Status {
    pub fn label(self) -> &'static str {
        match self {
            Status::ClosedByHardening => "closed-by-hardening",
            Status::Open => "open",
        }
    }
}

pub fn derive(attacks: &[Attack]) -> Vec<Finding> {
    let mut groups: BTreeMap<(Family, &'static str), Vec<&Attack>> = BTreeMap::new();
    for a in attacks.iter().filter(|a| a.shipped == Verdict::Landed) {
        groups.entry((a.family, a.technique)).or_default().push(a);
    }
    let mut counters: BTreeMap<Family, u32> = BTreeMap::new();
    let mut out = Vec::new();
    for ((family, technique), members) in groups {
        let n = counters.entry(family).or_insert(0);
        *n += 1;
        let severity = members
            .iter()
            .map(|a| a.severity)
            .max()
            .unwrap_or(Severity::Low);
        let status = if members.iter().all(|a| a.hardened == Verdict::Blocked) {
            Status::ClosedByHardening
        } else {
            Status::Open
        };
        out.push(Finding {
            id: format!("F-{}-{:02}", family.prefix(), n),
            family,
            technique,
            severity,
            witnesses: members.iter().map(|a| a.id.clone()).collect(),
            intent: members[0].intent,
            status,
        });
    }
    out.sort_by(|a, b| b.severity.cmp(&a.severity).then(a.id.cmp(&b.id)));
    out
}

pub fn render(findings: &[Finding], report: &crate::Report) -> String {
    let mut s = String::new();
    s.push_str("# Findings register\n\n");
    s.push_str(
        "Generated by `cargo run --bin redteam -- --write` from the corpus in \
`security/src/corpus/`. Do not edit by hand: a finding exists because an attack \
row lands on the shipped code, and it closes when the row's hardened column \
blocks it.\n\n",
    );
    s.push_str(&format!(
        "**{} attacks.** Shipped: {} blocked, {} landed. Hardened: {} blocked, {} landed. \
Drift: {}.\n\n",
        report.total,
        report.shipped_blocked,
        report.shipped_landed,
        report.hardened_blocked,
        report.hardened_landed,
        report.drift.len()
    ));
    s.push_str("| Family | Attacks | Shipped blocked | Shipped landed | Hardened landed |\n");
    s.push_str("|---|---:|---:|---:|---:|\n");
    for f in &report.by_family {
        s.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            f.family, f.total, f.shipped_blocked, f.shipped_landed, f.hardened_landed
        ));
    }
    s.push('\n');
    let open = findings.iter().filter(|f| f.status == Status::Open).count();
    s.push_str(&format!(
        "## {} findings ({} closed by the hardened layer, {} open)\n\n",
        findings.len(),
        findings.len() - open,
        open
    ));
    s.push_str("| Id | Severity | Family | Technique | Witnesses | Status |\n");
    s.push_str("|---|---|---|---|---:|---|\n");
    for f in findings {
        s.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} |\n",
            f.id,
            f.severity,
            f.family,
            f.technique,
            f.witnesses.len(),
            f.status.label()
        ));
    }
    s.push_str("\n## Detail\n\n");
    for f in findings {
        s.push_str(&format!(
            "### {} — {} ({}, {})\n\n{}\n\nWitnesses: {}\n\n",
            f.id,
            f.technique,
            f.severity,
            f.status.label(),
            capitalize(f.intent),
            f.witnesses.join(", ")
        ));
    }
    s
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}
